version: '2'

services:
  mysql-master:
    image: 'bitnami/mysql:5.7.24-ol-7'
    ports:
      - '3306'
    volumes:
      - /home/opc/mysql/data:/bitnami/mysql/data
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
  mysql-slave:
    image: 'bitnami/mysql:5.7.24-ol-7'
    ports:
      - '3306'
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password
  phpmyadmin:
    image: 'bitnami/phpmyadmin:latest'
    depends_on: 
      - mysql-master
    ports:
      - '80:80'
      - '443:443'
    environment:
      - PHPMYADMIN_ALLOW_NO_PASSWORD=false
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=false
      - DATABASE_HOST=mysql-master
    volumes:
      - /home/opc/phpmyadmin/data:/bitnami/
